server:
  port: 8888
spring:
  application:
    name: "hello-world"
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      server:
        git:
          skip-ssl-validation: false
          uri: https://github.com/hachim-soutra/spring-server-config
